# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'campGuide' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for campGuide

  pod 'GoogleMaps'
  target 'campGuideTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'campGuide-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for campGuide-tvOS

  target 'campGuide-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
